#!/bin/bash
# ensure you are a regular user, else quit
if [ $(whoami) == "root" ]; then
  echo "You must run this script as your regular user"
  exit 1
fi

source ~/venv/kolla/bin/activate

# install kolla (need to config globals.yml first)
# kolla-ansible -i all-in-one bootstrap-servers
# kolla-ansible -i all-in-one prechecks && kolla-ansible -i all-in-one deploy && kolla-ansible -i all-in-one post-deploy

