# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.provision "shell",
        inline: "hostnamectl set-hostname node-#{i}"
    config.vm.network "private_network", ip: "192.168.33.1#{i}"
    end
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    apt-get update
#    apt-get install -y screen tmux tree netcat nmap
#  SHELL
end
