# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"
    end
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    apt-get update
#    apt-get install -y screen tmux tree netcat nmap
#  SHELL
end
