# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # define CentOS Stream 8 VM
  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos8"
    centos.vm.hostname = "centos-vm"
    centos.vm.network "private_network", ip: "192.168.33.11"
  end

  # define Ubuntu 20.04 Vm
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.hostname = "ubuntu-vm"
    ubuntu.vm.network "private_network", ip: "192.168.33.12"
  end

  # Virtualbox-specific parameters
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus    = "1"
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

end
